In [2]:
import numpy as np
import os
array31 = np.arange(12).reshape(4, 3)
print("Array before:")
print(array31)
header = '0ne Two Three'
np.savetxt('temp.txt', array31, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Array before:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
