In [1]:
import numpy as np
matrix_1_31=np.array([[5,3,2],[6,3,8]])
matrix_2_31=np.array([[6,8,3],[5,7,1]])
print("array1 :")
print(matrix_1_31)
print("array2 :")
print(matrix_1_31)
print("result")
print(np.multiply(mat1_53,mat2_53))

array1 :
[[5 3 2]
 [6 3 8]]
array2 :
[[5 3 2]
 [6 3 8]]
result


NameError: name 'mat1_53' is not defined